# Generated by Django 5.0.3 on 2025-04-14 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorjiZZZ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_pic', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductWomen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_pic', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorjiZZZ.items'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_pic',
            field=models.ImageField(blank=True, default='images/Default_pic.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('shipping_address', models.TextField(max_length=200)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('bank', 'bank'), ('nagad', 'nagad'), ('COD', 'COD'), ('rocket', 'rocket')], default='COD', max_length=30, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorjiZZZ.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nid', models.CharField(default='12345', max_length=5)),
                ('contact_no', models.CharField(blank=True, default='+880', max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('about_myself', models.TextField(blank=True, default='will add later', null=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
